---
- name: installation d'Apache
  apt:
    name: apache2
    state: present

- name: Start Apache
  service:
    name: apache2
    state: started

- name: Shell pour apache2
  shell: service apache2 status
  register: apache2

- name: verif
  debug:
    msg: "{{apache2.stdout}}"

- name: Template page web
  template:
    src: template/index.html.j2
    dest: /var/www/html/index.html

- name: Copie du fichier txt
  copy:
    src: files/toto.txt
    dest: /tmp/tata.txt
