---
- hosts: webserver
  remote_user: root
  vars_files:
         - "vars/{{env}}_vars.yml"
         - "vars/{{env}}_secret.yml"
  roles:
       #- role: create_user
       # - role: install_vim
         - role: apache_install
       # - role: apache_template         
