---
- name: installation d'Apache
  apt:
    name: apache2
    state: present

- name: Start Apache
  service:
    name: apache2
    state: started

- name: Shell pour apache2
  shell: service apache2 status
  register: apache2

- name: verif
  debug:
    msg: "{{apache2.stdout}}"
