---
#- hosts: webserver
#  remote_user: root
#  vars_files:
#          - "vars/{{env}}_vars.yml"
#  tasks:
#   - name: debug
#     debug:
#       msg: "bonjour ici l'environnement {{env}}"
#   - name: vim installation / desinstallation
#     apt:
#        name: vim
#        state: "{{vim_state}}"

- hosts: webserver
  remote_user: root
  vars_files:
          # - "vars/{{env}}_vars.yml"
         - "vars/{{env}}_secret.yml"
  tasks:         
    - name: Create a login user
      user:
        name: "{{username}}"
        password: "{{ password | password_hash('sha512') }}"
        createhome: yes
      register: recap

    - name: ok
      debug:
        msg: "{{recap}}"

