---
- name: Create a login user
  user:      
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    createhome: yes
  loop:
     - username: "{{username1}}"
       password: "{{password1}}"
     - username: "{{username2}}"
       password: "{{password2}}"
  register: recap
  when: ansible_facts['distribution'] == "Ubuntu"

- name: ok
  debug:
    msg: "{{recap}}"

